# variaveis_python.py
print("Tipos de variáveis em Python:")


# INTEGER (int)
print(" - int: Inteiros, representados por números sem casas decimais, como 10, -3, 42.")
numero = 10
print(type(numero))
print("Integer (int):", numero)
print("Operações com int:")
print(" - Adição:", numero + 5)
print(" - Subtração:", numero - 3)
print(" - Multiplicação:", numero * 2)
print(" - Divisão:", numero / 3)
print(" - Potência:", numero ** 2)
print(" - Módulo:", numero % 3)

# FLOAT (float)
print(" - float: Valores de ponto flutuante, ou números decimais, como 3.14, -0.001, 2.0.")
decimal = 10.5
print(type(decimal))
print("\nFloat (float):", decimal)
print("Operações com float:")
print(" - Adição:", decimal + 2.5)
print(" - Subtração:", decimal - 1.2)
print(" - Multiplicação:", decimal * 3.1)
print(" - Divisão:", decimal / 2.0)
print(" - Arredondar (round):", round(decimal, 1))

# BOOLEAN (bool)
print(" - bool: Booleanos, representando valores lógicos True (verdadeiro) ou False (falso).")
flag = True
print(type(flag))
print("\nBoolean (bool):", flag)
print("Operações com bool:")
print(" - Negação (not):", not flag)
print(" - E lógico (and):", flag and False)
print(" - Ou lógico (or):", flag or False)
print("Funções any e all:")
print(" - any([True, False, False]):", any([True, False, False]))
print(" - all([True, True, False]):", all([True, True, False]))

# STRING (str)
print(" - str: Strings, ou sequências de caracteres, para texto, como 'Python', 'exemplo'.")
texto = "Python"
print(type(texto))
print("\nString (str):", texto)
print("Métodos de string:")
print(" - Upper:", texto.upper())
print(" - Lower:", texto.lower())
print(" - Título:", texto.title())
print(" - Substituir:", texto.replace("Python", "Coding"))
print(" - Tamanho (len):", len(texto))
print(" - Checar prefixo (startswith):", texto.startswith("Py"))

# LISTA (list)
print(" - list: Listas, coleções ordenadas e mutáveis de elementos, como [1, 2, 'a', True].")
lista = [1, 2, 3, 4]
print(type(lista))
print("\nLista (list):", lista)
print("Métodos de lista:")
print(" - Adicionar (append):", lista.append(5), lista)
print(" - Inserir (insert):", lista.insert(1, "novo"), lista)
print(" - Remover (remove):", lista.remove("novo"), lista)
print(" - Tamanho (len):", len(lista))
print(" - Ordenar (sort):", lista.sort(reverse=True), lista)
print(" - Reverter (reverse):", lista.reverse(), lista)

# TUPLA (tuple)
print(" - tuple: Tuplas, coleções ordenadas e imutáveis, como (1, 2, 3) ou ('a', 'b').")
tupla = (1, 2, 3)
print(type(tupla))
print("\nTupla (tuple):", tupla)
print("Operações com tupla:")
print(" - Acesso por índice:", tupla[1])
print(" - Contagem de valor (count):", tupla.count(2))
print(" - Índice do valor (index):", tupla.index(3))
print("Nota: Tuplas são imutáveis!")

# DICIONÁRIO (dict)
print(" - dict: Dicionários, coleções de pares chave-valor, como {'chave': 'valor'}.")
dicionario = {"chave": "valor", "idade": 25}
print(type(dicionario))
print("\nDicionário (dict):", dicionario)
print("Métodos de dicionário:")
print(" - Acessar valor:", dicionario.get("idade"))
print(" - Adicionar par chave-valor:", dicionario.update({"nome": "Alice"}), dicionario)
print(" - Chaves (keys):", list(dicionario.keys()))
print(" - Valores (values):", list(dicionario.values()))
print(" - Remover (pop):", dicionario.pop("idade"), dicionario)

# CONJUNTO (set)
print(" - set: Conjuntos, coleções desordenadas e sem valores duplicados, como {1, 2, 3}.")
conjunto = {1, 2, 3}
print(type(conjunto))
print("\nConjunto (set):", conjunto)
print("Métodos de conjunto:")
print(" - Adicionar elemento (add):", conjunto.add(4), conjunto)
print(" - Remover elemento (discard):", conjunto.discard(1), conjunto)
print(" - União com outro conjunto:", conjunto.union({3, 5}))
print(" - Interseção com outro conjunto:", conjunto.intersection({3, 4, 5}))
print(" - Diferença com outro conjunto:", conjunto.difference({3, 4, 5}))
print(" - Diferença simétrica com outro conjunto:", conjunto.symmetric_difference({3, 5}))
